services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: Uptime-Kuma-MRP
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3003:3001
    restart: unless-stopped
